name: Bug report
description: Report a problem with create-seamless
title: "[Bug]: "
labels: ["bug"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report an issue.

  - type: input
    id: version
    attributes:
      label: create-seamless version
      description: Output of `create-seamless --version`
      placeholder: "0.4.0"
    validations:
      required: true

  - type: input
    id: node
    attributes:
      label: Node.js version
      placeholder: "20.11.0"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: What happened?
      description: Describe the bug clearly and concisely.
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: What did you expect to happen?
    validations:
      required: false

  - type: textarea
    id: logs
    attributes:
      label: Logs / stack traces
      render: shell
    validations:
      required: false
